### ISSUE TITLE
02 - run-app - Bat out of hell

### ISSUE THREAD

**Issue by devantler** [harpunfiskeren/simple-fortune-cookie#2]
## Bat out of hell

Not completely without luck, you find that the previous developers have actually
    created README's for their code!

Try that and see how that flies for you.

### Task

- Install go on your cloud instance
- Build with `go build`
- Run both the frontend and backend with `go run ..`
- Familiarize yourself with the application (frontend and backend, try to add a cookie and re-run the backend)

**Comment by Hounsvad** [comment]
This is a test
